// src/frontend/src/routes/scan/+page.svelte
<script>
    import { CameraPreview} from "@capacitor-community/camera-preview"
    import QrScanner from "qr-scanner"
    import { onMount } from "svelte"

    let decoded = "Awaiting"

    function goBack() {
        CameraPreview.stop()
        window.location.href = "/dashboard"
    }
    
    async function scan() {
        decoded = "awaiting"
        let data = await CameraPreview.capture({quality: 100})
        .then(result => "data:image/jpeg;base64," + result.value)
        
        let image = await fetch(data)
        .then(data => data.blob())
        .then(data => createImageBitmap(data))



        QrScanner.scanImage(image)
        .then(result => decoded = JSON.parse(result).amount)
        .catch(err => decoded = err)





    }
    onMount(
        () => CameraPreview.start({ parent: "cameraPreview", toBack: true})
    )

</script>
<div id="overlay">
</div>
<div id="button-container">
    <!-- For debugging purposes only-->
    <p contenteditable="true" bind:innerText={decoded}>{decoded}</p>
    <button class="button" on:click={scan}>Scan</button>
    <button class="button" on:click|preventDefault={goBack}>Back</button>
</div>
<div id="cameraPreview">

</div>
    


<style>
    :global(html) {
        background-color: transparent !important;
    }
    :global(body) {
        background-color: transparent !important;
    }
    #canv {
        background-color: black;
        position: absolute;
    }
    #button-container {
        background-color: transparent;
        width: 100%;
        height: 60px;
        position: absolute;
        transform: translate(-50%, -50%);
        top: 95%;
        left: 50%;

        display: flex;
        direction: row;
        align-items: center;
        justify-content: space-evenly;
    }
    #cameraPreview {
        background-color: transparent;
    }
    #overlay {
        background-color: transparent;
        height: 200px;
        width: 200px;
        border: dashed 4px rgba(235, 235, 235, 0.644);
        border-radius: 10px;
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .button {
        padding: 5px 10px 5px 10px;
    }
</style>

// src/frontend/src/views/Scan.vue
<template>
  <ion-page class="transparent">
    <ion-content class="transparent">
      <div id="camera"></div>
      <ion-button fill="outline" size="large" id="scan-button" @click="handleScan">Scan</ion-button>
    </ion-content>
  </ion-page>

</template>

<script setup lang="ts">
  import {
  IonButton,
  IonPage,
  IonContent,
  } from '@ionic/vue';
  import { onMounted } from 'vue';
  import { CameraPreview } from '@capacitor-community/camera-preview';
  import { useBackButton } from '@ionic/vue';
  import QrScanner from "qr-scanner";
  import { makeTransaction } from "@/maketransaction";
  import router from '@/router';
  
  async function scan() {
    // Get take the picture
    let data = await CameraPreview.capture({quality: 100})
    .then(result => "data:image/jpeg;base64," + result.value)
    .catch(err => console.log(err))
    
    // Convert to BLOB
    let image = await fetch(data)
    .then(data => data.blob())
    .then(data => createImageBitmap(data))
    .catch(err => console.log(err))

    // Scans the image for a QR code
    let result = await QrScanner.scanImage(image)
    .catch(err => console.log(error))

    //The function to create a transaction goes HERE!!!
    return JSON.parse(result)

  }

  async function handleScan() {
    let data = await scan()
    let response = await makeTransaction(data)
    
    if (response == "success") {
      CameraPreview.stop()
      // Add a success view later
      router.replace({ path: "/dashboard" })
    }
  }

  onMounted(
    () => {
      CameraPreview.start({parent: "camera", toBack: true})

    }
  )
  
  // Stop the camera whenever the back button is pressed.
  // If this is not done, it causes all sorts of badness. DO NOT TOUCH
  useBackButton(0, () => {
    CameraPreview.stop()
    router.replace({ path: "/dashboard" })
  })

</script>

<style scoped>
  #scan-button {
    position: absolute;
    transform: translate(-50%,0%);
    bottom: 40px;
    left: 50%;
    z-index: 1000;

  }
  .transparent {
    background-color: transparent;
  }

</style>
