// src/frontend/src/views/Receive.vue
<template>
<ion-page>
  <ion-content>

    <ion-header>
      <ion-toolbar>
        <ion-button 
        slot="start"
        router-link="/dashboard"
        router-direction="back"
        fill="clear"
        shape="round">
          <ion-icon :icon="arrowBack"></ion-icon>
        </ion-button>
      </ion-toolbar>
    </ion-header>

    <ion-grid>
      <ion-row class="QR">
        <ion-col class="QR" size="12">
          <canvas id="canvas"></canvas>
        </ion-col>
      </ion-row>

      <ion-row>
          <ion-col size="12">
          <ion-input :value="amount" fill="outline" label="Ammount" label-placement="floating" placeholder="00.00" type="number"></ion-input>
          </ion-col>
      </ion-row>

      <ion-row>
          <ion-col size="12">
          <ion-button @click="generate_code" id="generate-qr">Generate a QR code</ion-button>
          </ion-col>
      </ion-row>
    </ion-grid>
  </ion-content>
</ion-page>


</template>

<script setup lang="ts">
  import {
  IonInput,
  IonGrid,
  IonRow,
  IonCol,
  IonButton,
  IonPage,
  IonContent,
  IonHeader,
  IonToolbar,
  IonIcon
  } from '@ionic/vue';
  import { arrowBack } from 'ionicons/icons';
  import { store } from '@/store';
  import * as QRCode from 'qrcode';


  let amount: string;
  
  function generate_code() {
    let data = `{ "payee": ${store.account.number}, "amount": ${parseFloat(amount)} }`

    let canvas = document.getElementById("canvas")

    let options = {
      scale: 10
    }
    QRCode.toCanvas(canvas, data, options, err => console.error(err))
  }

</script>

<style scoped>
#generate-qr {
  width: 100%;
}
.QR {
  height: 500px !important;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>

// src/frontend/src/routes/receive/+page.svelte
<script>
import * as QRCode from 'qrcode'
import { account } from '../../stores';
    
let inputValue = "0.0";

async function generateQR() {
    let data = `{ "payee": ${$account.number}, "amount": ${inputValue}}`
    
    const canvas = document.getElementById('canvas')

    document.getElementById("form")?.classList.toggle("hidden")
    document.getElementById("canvas")?.classList.toggle("hidden")
    
    QRCode.toCanvas(canvas, data, (error) => console.error(error))
}

function handleClear() {
    // Handle clear button logic
    inputValue = "0.0";

}
</script>
<div id="container" >
    <canvas class="hidden" id="canvas"></canvas>
    <form id="form" class="form" action="" on:submit|preventDefault={generateQR}>
    <input type="number" class="form-input" name="amount" bind:value={inputValue} />
    <div class="button-container">
        <button class="submit-button">Generate</button>
        <button class="clear-button" on:click={handleClear}>Clear</button>
    </div>
    </form>
</div>

<style>
    .hidden {
        visibility: hidden;
        max-width: 1px;
        max-height: 1px;
    }
    .form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 50vh;
    }

    .form-input {
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 4px;
        padding: 8px;
        font-weight: 500;
        color: #585858;
        transition: border-color 0.3s, color 0.3s;
        -webkit-appearance: none;
        appearance: textfield;
        text-align: right;
        margin-top: 5px;
    }

    .form-input:focus {
        outline: 2px solid black;
        border-color: black;
    }

    .button-container {
        display: flex;
        direction: row;
        align-items: center;
        justify-content: space-between;
        padding: 15px;
        width: 200px;
    }

    .submit-button,
    .clear-button {
        padding: 10px;
        font-size: 18px;
    }
    #container {
        display: flex;
        align-items: center;
        justify-content: center;
        height: 100%;
    }
    #canvas {
        height: 256px !important;
        width: 256px !important;
    }
</style>
